//1 . Services Actions
export const GET_ERRORS="GET_ERRORS";
export const GET_ALL_SERVICES="GET_ALL_SERVICES";
export const GET_SERVICE_BY_ID="GET_SERVICE_BY_ID";
export const DELETE_SERVICE_BY_ID="DELETE_SERVICE_BY_ID";

//Employee Actions

export const GET_ALL_EMPLOYEES="GET_ALL_EMPLOYEES";
export const GET_EMPLOYEE_BY_ID="GET_EMPLOYEE_BY_ID";
export const DELETE_EMPLOYEE_BY_ID="DELETE_EMPLOYEE_BY_ID";