// Common
export const GET_ERRORS = "GET_ERRORS";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

//1. Login Actionss
export const SET_CURRENT_COMPANY = "SET_CURRENT_COMPANY";
export const LOGIN = "LOGIN";

//2. Services Actions
export const GET_ALL_SERVICES = "GET_ALL_SERVICES";
export const GET_SERVICE_BY_ID = "GET_SERVICE_BY_ID";
export const DELETE_SERVICE_BY_ID = "DELETE_SERVICE_BY_ID";

//3. Company Actions
export const GET_COMPANY_SERVICE_BY_COMPANY_CODE = "GET_COMPANY_SERVICE_BY_COMPANY_CODE";

//4. Employee Actions

export const GET_ALL_EMPLOYEES = "GET_ALL_EMPLOYEES";
export const GET_ALL_COMPANY_EMPLOYEE = "GET_ALL_COMPANY_EMPLOYEE";
export const GET_EMPLOYEE_BY_EMPLOYEE_CODE = "GET_EMPLOYEE_BY_EMPLOYEE_CODE";
export const DELETE_EMPLOYEE_BY_ID = "DELETE_EMPLOYEE_BY_ID";

//5. Company Employee Service Actions
export const GET_COMPANY_EMPLOYEE_SERVICE = "GET_COMPANY_EMPLOYEE_SERVICE";

//6. Asset Actions
export const GET_ALL_ASSETS = "GET_ALL_ASSETS";
export const GET_ALL_ASSETS_BY_COMPANY_CODE = "GET_ALL_ASSETS_BY_COMPANY_CODE";
export const GET_ASSET_BY_ASSET_CODE = "GET_ASSET_BY_ASSET_CODE";
export const DELETE_ASSET_BY_ASSET_CODE = "DELETE_ASSET_BY_ASSET_CODE";

//7. Dashboard Actions
export const GET_DASHBOARD_REPORT = "GET_DASHBOARD_REPORT";


//8. Service Request Actions
export const GET_ALL_SERVICE_REQUEST="GET_ALL_SERVICE_REQUEST";
export const POST_ASSIGN_EMPLOYEE_REQUEST="POST_ASSIGN_EMPLOYEE_REQUEST";
export const GET_ALL_AVAILABLE_EMPLOYEE = "GET_ALL_AVAILABLE_EMPLOYEE";

//9. Time Slots
export const GET_COMPANY_AVAILABLE_TIME_SLOTS_BY_DATE="GET_COMPANY_AVAILABLE_TIME_SLOTS_BY_DATE";
export const POST_GENERATE_COMPANY_TIME_SLOTS_FOR_DATE = "POST_GENERATE_COMPANY_TIME_SLOTS_FOR_DATE";


