// Common
export const GET_ERRORS = "GET_ERRORS";

//1 . Services Actions
export const GET_ALL_SERVICES = "GET_ALL_SERVICES";
export const GET_SERVICE_BY_ID = "GET_SERVICE_BY_ID";
export const DELETE_SERVICE_BY_ID = "DELETE_SERVICE_BY_ID";

//2. Company Actions
export const GET_COMPANY_SERVICE_BY_COMPANY_CODE = "GET_COMPANY_SERVICE_BY_COMPANY_CODE";

//3. Employee Actions

export const GET_ALL_EMPLOYEES = "GET_ALL_EMPLOYEES";
export const GET_ALL_COMPANY_EMPLOYEE = "GET_ALL_COMPANY_EMPLOYEE";
export const GET_EMPLOYEE_BY_ID = "GET_EMPLOYEE_BY_ID";
export const DELETE_EMPLOYEE_BY_ID = "DELETE_EMPLOYEE_BY_ID";

//4. Employee Actions
export const GET_EMPLOYEE_SERVICE_BY_COMPANY_CODE = "GET_EMPLOYEE_SERVICE_BY_COMPANY_CODE";

//5. Asset Actions
export const GET_ALL_ASSETS = "GET_ALL_ASSETS";
export const GET_ALL_ASSETS_BY_COMPANY_CODE = "GET_ALL_ASSETS_BY_COMPANY_CODE";
export const GET_ASSET_BY_ASSET_CODE = "GET_ASSET_BY_ASSET_CODE";
export const DELETE_ASSET_BY_ASSET_CODE = "DELETE_ASSET_BY_ASSET_CODE";